title: Blog
email: marina.milette@gmail.com
description: Just things
author: Marina Milette-Morin
# baseurl:            "/startbootstrap-clean-blog-jekyll"
# url:                "https://startbootstrap.github.io"
repository: Avalai/Avalai.github.io

# Social Profiles
twitter_username: Avalai
github_username: Avalai
instagram_username: Avalai
linkedin_username: marinamilette

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-remote-theme

# theme: jekyll-theme-clean-blog
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

collections_dir: collections
collections:
  mushroom_books:
    sort_by: title
